import os
import sys

from dotenv import load_dotenv
from google import genai
from google.genai import types
from Functions.get_files_info import schema_get_files_info
from Functions.get_file_content import schema_get_file_content
from Functions.write_file import schema_write_file
from Functions.run_python_file import schema_run_python_file



def main():
    load_dotenv() # Load the variables stored in the .env file
    api_key = os.environ.get("GEMINI_API_KEY") # Get the Gemini API key from the environment
    client = genai.Client(api_key=api_key) # Create a Gemini client using our API key

    # general guide for the AI Agent
    system_prompt = """
        You are a helpful AI coding agent.

        When a user asks a question or makes a request, make a function call plan. You can perform the following operations:

        - List files and directories

        All paths you provide should be relative to the working directory. You do not need to specify the working directory in your function calls as it is automatically injected for security reasons.
    """

    if len(sys.argv) < 2:
        print("I need a prompt!")
        sys.exit(1)
    # sys.argv[0] = name of the Python file
    # sys.argv[1] = user's prompt
    # If the user doesn't provide a prompt, stop the program
    prompt=sys.argv[1]

    verbose_flag = False
    
    if len(sys.argv) == 3 and sys.argv[2] == "--verbose":
        verbose_flag = True

    messages=[ # Create a message that Gemini can understand
        types.Content(
            role="user", # role="user" tells Gemini that this message came from the user
            parts=[types.Part(text=prompt)]
        ),
    ]

    available_functions = types.Tool(
        function_declarations=[
            schema_get_files_info,
            schema_get_file_content,
            schema_write_file,
            schema_run_python_file,
        ]
    )

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=messages,
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            tools=[available_functions],
        ),
    )

    # Make sure usage information exists before accessing it
    if response is None or response.usage_metadata is None:
            print("Response is malformed")
            return
    
    if verbose_flag:
            print(f"User prompt: {prompt}") # Print the user's prompt in verbose mode
            print( # Number of tokens used by the prompt
                f"Prompt tokens: "
                f"{response.usage_metadata.prompt_token_count}"
            )
            print( #  Number of tokens generated by Gemini
                f"Response tokens: "
                f"{response.usage_metadata.candidates_token_count}"
            )
        
    if response.function_calls:
        for function_call_part in response.function_calls:
            print(
                f"Calling function: {function_call_part.name}({function_call_part.args})"
            )
    else:
        print(response.text)


if __name__ == "__main__":
    main()
    # Run main() when this file is executed directly