import os
import sys

from dotenv import load_dotenv
from google import genai
from google.genai import types


def main():
    load_dotenv() # Load the variables stored in the .env file
    api_key = os.environ.get("GEMINI_API_KEY") # Get the Gemini API key from the environment
    client = genai.Client(api_key=api_key) # Create a Gemini client using our API key

    if len(sys.argv) < 2:
        print("I need a prompt!")
        sys.exit(1)
    # sys.argv[0] = name of the Python file
    # sys.argv[1] = user's prompt
    # If the user doesn't provide a prompt, stop the program
    prompt=sys.argv[1]

    verbose_flag = False
    
    if len(sys.argv) == 3 and sys.argv[2] == "--verbose":
        verbose_flag = True

    messages=[ # Create a message that Gemini can understand
        types.Content(
            role="user", # role="user" tells Gemini that this message came from the user
            parts=[types.Part(text=prompt)]
        ),
    ]

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=messages,
    )
    print(response.text)

    if response is None or response.usage_metadata is None:
        return
    # Make sure usage information exists before accessing it

    if verbose_flag:
        print(f"User prompt: {prompt}") # Print the user's prompt in verbose mode
        print( # Number of tokens used by the prompt
            f"Prompt tokens: "
            f"{response.usage_metadata.prompt_token_count}"
        )
        print( #  Number of tokens generated by Gemini
            f"Response tokens: "
            f"{response.usage_metadata.candidates_token_count}"
        )


if __name__ == "__main__":
    main()
    # Run main() when this file is executed directly