import os
# os allows Python to interact with environment variables

from dotenv import load_dotenv
# load_dotenv() reads variables from our .env file and loads them
# into the environment so our Python program can access them

from google import genai
# genai is Google's Python SDK for communicating with Gemini models


load_dotenv()
# Load the variables stored inside .env

api_key = os.environ.get("GEMINI_API_KEY")
# Get the value of GEMINI_API_KEY from the environment
# api_key now contains our actual Gemini API key


print("API key loaded:", bool(api_key))

client = genai.Client(api_key=api_key)
# Create a Gemini client
# The client uses our API key to authenticate requests to Google's Gemini API
print("Sending request...")

response = client.models.generate_content(
    model="gemini-3.6-flash",
    # Specify which Gemini model we want to use
    contents="Why is the sky blue?"
    # This is the prompt/question that we are sending to Gemini
)

print("Got response")
print(response.text)

print(f"Prompt tokens: {response.usage_metadata.prompt_token_count}")
# Number of tokens that were sent to Gemini as input
print(f"Response tokens: {response.usage_metadata.candidates_token_count}")
# Number of tokens generated by Gemini as output